### ISSUE TITLE
errors when testing onnx models

### ISSUE THREAD

**Issue by piuz** [CoCoPIE-Group/XGen-Report#20]
I find some onnx models on github. Here is the link: https://github.com/onnx/models 
It is a onnx model zoo with many onnx models. However, if I use XGen to test these models with the command:
```
XGen test-onnx-latency  --model-path /root/Projects/onnx/    --output-path /root/Projects/onnx_results/
```
I always have the same error, the results are attached. 
[result_github_onnx.csv](https://github.com/CoCoPIE-Group/XGen-Report/files/9693644/result_github_onnx.csv)
All the models are collected from the above github link with the same model name. 

amazon aws also provides some onnx models. 
I downloaded two onnx models from amazon aws with the following link
```
wget https://s3.amazonaws.com/onnx-model-zoo/vgg/vgg16/vgg16.onnx
wget https://s3.amazonaws.com/onnx-model-zoo/resnet/resnet50v1/resnet50v1.onnx
```
It still have some errors to test their latency with XGen following the command,
```
XGen test-onnx-latency  --model-path /root/Projects/onnx/    --output-path /root/Projects/onnx_results/
```
I just put the downloaded aws onnx model in the model-path directory and delete other models. The results are attached. 
[result_aws_resnet_onnx.csv](https://github.com/CoCoPIE-Group/XGen-Report/files/9693650/result_aws_resnet_onnx.csv)
[result_aws_vgg_onnx.csv](https://github.com/CoCoPIE-Group/XGen-Report/files/9693651/result_aws_vgg_onnx.csv)

**Comment by xipengshen** [comment]
@piuz Our compiler library expired on 9/30. Please upgrade your XGen: 
https://xgen.cocopie.ai/2_Installation/#how-to-upgrade-xgen

**Comment by xipengshen** [comment]
@EthanGuan With the latest XGen, I saw the same errors as Pu reported. It seems to be errors from the compiler. Can you check it?

**Comment by EthanGuan** [comment]
1. The Error message might be related to a incorrect protobuf version is installed. Recently, protobuf packages of version 4.x have been released. Please check your protobuf version. If it is version 4.x, please downgrade it to 3.20.3.
2. Those ONNX files are no longer supported by most frameworks, including MNN that I tested recently.  Because its ONNX `IR version` is too old (version 3), compare to the lastest (version 8). I found a tool that might be able to transform the IR version(https://github.com/PINTO0309/simple-onnx-processing-tools). For ONNX IR version, please refer to this link: https://github.com/onnx/onnx/blob/main/docs/Versioning.md#released-versions.
3. We can messege to users that the ONNX is not supported by our compier frontend according to its IR version.
4. The ONNX models have dynamic batch sizes, we cannot adjust its value to static as the IR version is old.

**Comment by xipengshen** [comment]
Please see the following issue about how to export onnx compatible with XGen: 
https://github.com/CoCoPIE-Group/XGen-Report/issues/23
